import type { V2ControllerKind } from "./v2-levels.generated";

export const DIRECTOR_SPATIAL_STATES = Object.freeze([
  "idle",
  "probe",
  "armed",
  "running",
  "stopped",
  "success",
  "miss",
] as const);

export type DirectorSpatialState = (typeof DIRECTOR_SPATIAL_STATES)[number];
export type DirectorChapterNumber = 1 | 2 | 3 | 4 | 5 | 6;
export type DirectorRole = "teach" | "twist" | "compose" | "master";
export type DirectorSolveShape = "single-action" | "sequence" | "concurrent" | "stateful";
export type DirectorTraceId = `TH-DC-${string}`;

export interface DirectorChapter {
  number: DirectorChapterNumber;
  title: { zh: string; en: string };
  thesis: string;
  firstSolveTargetSeconds: { min: number; max: number };
}

interface DirectorHint {
  content: string;
  revealsAction: boolean;
}

export interface DirectorLevelDefinition {
  traceId: DirectorTraceId;
  number: number;
  chapter: DirectorChapterNumber;
  role: DirectorRole;
  legacyId: number;
  legacySlug: string;
  controller: V2ControllerKind;
  evidence: readonly string[];
  hypotheses: readonly string[];
  reasoningSteps: readonly string[];
  negativeFeedback: readonly string[];
  hints: {
    h0: DirectorHint;
    h1: DirectorHint;
    h2: DirectorHint;
    h3: DirectorHint;
  };
  solveShape: DirectorSolveShape;
  firstSolveTargetSeconds: { min: number; max: number };
  knownAnswerMaxSeconds: number;
  inputModes: readonly ["pointer", "touch", "keyboard"];
  reducedMotionEquivalent: true;
  spatialProof: string;
  acceptance: readonly string[];
}

type DirectorLevelInput = Omit<
  DirectorLevelDefinition,
  "inputModes" | "reducedMotionEquivalent"
>;

const INPUT_MODES = Object.freeze(["pointer", "touch", "keyboard"] as const);

function freezeHint(content: string, revealsAction: boolean): DirectorHint {
  return Object.freeze({ content, revealsAction });
}

function defineLevel(input: DirectorLevelInput): DirectorLevelDefinition {
  return Object.freeze({
    ...input,
    evidence: Object.freeze([...input.evidence]),
    hypotheses: Object.freeze([...input.hypotheses]),
    reasoningSteps: Object.freeze([...input.reasoningSteps]),
    negativeFeedback: Object.freeze([...input.negativeFeedback]),
    hints: Object.freeze({
      h0: freezeHint(input.hints.h0.content, false),
      h1: freezeHint(input.hints.h1.content, false),
      h2: freezeHint(input.hints.h2.content, false),
      h3: freezeHint(input.hints.h3.content, true),
    }),
    firstSolveTargetSeconds: Object.freeze({ ...input.firstSolveTargetSeconds }),
    inputModes: INPUT_MODES,
    reducedMotionEquivalent: true,
    acceptance: Object.freeze([...input.acceptance]),
  });
}

export const DIRECTOR_CHAPTERS = Object.freeze([
  {
    number: 1,
    title: { zh: "页面醒来", en: "The Page Wakes" },
    thesis: "物体、静置、词义、影子、光和纸层都可能改变页面规则。",
    firstSolveTargetSeconds: { min: 25, max: 90 },
  },
  {
    number: 2,
    title: { zh: "关系机器", en: "Relation Machines" },
    thesis: "解答不在单个物体里，而在零点、耦合、边界、夹层和经过关系里。",
    firstSolveTargetSeconds: { min: 45, max: 150 },
  },
  {
    number: 3,
    title: { zh: "时间有形状", en: "Time Has Shape" },
    thesis: "把持续时间、节拍、相位和先后转译成距离、折叠与深度。",
    firstSolveTargetSeconds: { min: 60, max: 210 },
  },
  {
    number: 4,
    title: { zh: "注意力语言", en: "The Language of Attention" },
    thesis: "焦点、空白、双语层和并发输入成为可推理的控制语言。",
    firstSolveTargetSeconds: { min: 75, max: 240 },
  },
  {
    number: 5,
    title: { zh: "浏览器会记得", en: "The Browser Remembers" },
    thesis: "可见性、反向映射、滚轮、拓扑和重置共同构成页面记忆。",
    firstSolveTargetSeconds: { min: 90, max: 300 },
  },
  {
    number: 6,
    title: { zh: "时间花园", en: "The Time Garden" },
    thesis: "组合此前学会的遮挡、响应式、折叠、时间层、交集和负空间。",
    firstSolveTargetSeconds: { min: 120, max: 360 },
  },
] as const satisfies readonly DirectorChapter[]);

const C1 = DIRECTOR_CHAPTERS[0].firstSolveTargetSeconds;
const C2 = DIRECTOR_CHAPTERS[1].firstSolveTargetSeconds;
const C3 = DIRECTOR_CHAPTERS[2].firstSolveTargetSeconds;
const C4 = DIRECTOR_CHAPTERS[3].firstSolveTargetSeconds;
const C5 = DIRECTOR_CHAPTERS[4].firstSolveTargetSeconds;
const C6 = DIRECTOR_CHAPTERS[5].firstSolveTargetSeconds;

export const DIRECTOR_CAMPAIGN = Object.freeze([
  defineLevel({
    traceId: "TH-DC-001",
    number: 1,
    chapter: 1,
    role: "teach",
    legacyId: 1,
    legacySlug: "four-corner-breach",
    controller: "corner-repair",
    evidence: ["纸框右上角存在连续轮廓中的缺口", "轻压后缺口与页边碎片显出同向纸纤维"],
    hypotheses: ["缺口本身是开关", "页边碎片只是装饰", "先取得缺口证据再用碎片修复"],
    reasoningSteps: ["轻压缺口取得纸纤维方向", "用纤维连续性判断并装回页边碎片"],
    negativeFeedback: ["直接送入碎片时纸面仍未闭合并回弹", "轻压缺口只显出证据而不解锁"],
    hints: {
      h0: { content: "缺口与页边碎片共同构成谜面", revealsAction: false },
      h1: { content: "缺口的纸纤维短暂浮出", revealsAction: false },
      h2: { content: "页边碎片与缺口拥有同一段纤维方向", revealsAction: false },
      h3: { content: "先检查纸页缺口，再把页边纸片装回去", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C1,
    knownAnswerMaxSeconds: 8,
    spatialProof: "缺口证据显现后，页边纸片沿深度吸附并闭合纸框。",
    acceptance: ["直接放入不能过关", "第一屏不聚光页边纸片", "缺口与碎片触控区至少 44px"],
  }),
  defineLevel({
    traceId: "TH-DC-002",
    number: 2,
    chapter: 1,
    role: "twist",
    legacyId: 2,
    legacySlug: "breath-gap",
    controller: "patient-hold",
    evidence: ["有意义输入会让纸叶合紧", "静置后缝隙与气泡出现"],
    hypotheses: ["连续点击敲开", "直接拖开纸叶", "停止打扰后稳住气泡"],
    reasoningSteps: ["观察操作与合拢的因果", "静置后长按气泡完成呼吸"],
    negativeFeedback: ["密集点击让纸叶更紧", "提前松开只回到半开状态"],
    hints: {
      h0: { content: "输入与纸叶合拢直接共变", revealsAction: false },
      h1: { content: "停手后两叶各呼吸一次", revealsAction: false },
      h2: { content: "你做得越多，它藏得越深", revealsAction: false },
      h3: { content: "停手等待缝隙出现，再按住气泡", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C1,
    knownAnswerMaxSeconds: 8,
    spatialProof: "纸叶层间距随静置恢复，气泡成为稳定时间核心。",
    acceptance: ["后台时间不累计", "普通指针漂移不重置", "只强制等待一次"],
  }),
  defineLevel({
    traceId: "TH-DC-003",
    number: 3,
    chapter: 1,
    role: "teach",
    legacyId: 3,
    legacySlug: "slow-command",
    controller: "word-shift",
    evidence: ["FAST 字牌比世界漂得更快", "翻牌后影子速度随字义变化"],
    hypotheses: ["抓住整词", "重排字牌", "改写词义改变世界速度"],
    reasoningSteps: ["翻牌确认词与速度共变", "把 FAST 改写成 SLOW"],
    negativeFeedback: ["抓整词只会反弹", "无意义词使各牌速度不一致"],
    hints: {
      h0: { content: "词牌与世界速度共变", revealsAction: false },
      h1: { content: "四块翻页齿口依次轻压", revealsAction: false },
      h2: { content: "页面也许在照着这个词行动", revealsAction: false },
      h3: { content: "把 FAST 改成 SLOW", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C1,
    knownAnswerMaxSeconds: 10,
    spatialProof: "字牌与影子分层滑移，正确词合成慢速刻印。",
    acceptance: ["每牌翻一次不能误过", "开场不显示完整 SLOW 轮廓"],
  }),
  defineLevel({
    traceId: "TH-DC-004",
    number: 4,
    chapter: 1,
    role: "twist",
    legacyId: 4,
    legacySlug: "target-knock",
    controller: "shadow-sort",
    evidence: ["圆片大小与影长顺序相反", "移动后影子短暂留在纸面"],
    hypotheses: ["按圆片大小入窝", "按浅窝大小入窝", "按影长匹配阴影刻线"],
    reasoningSteps: ["用一次错误大小配对获得反证", "按照影长完成三组配对"],
    negativeFeedback: ["物体吻合但影子越界", "错误交换不清空已经正确的一组"],
    hints: {
      h0: { content: "物体移动后影子滞留", revealsAction: false },
      h1: { content: "三个浅窝的影线依次显色", revealsAction: false },
      h2: { content: "可靠的也许不是圆片本身", revealsAction: false },
      h3: { content: "按影子的长度匹配浅窝", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C1,
    knownAnswerMaxSeconds: 10,
    spatialProof: "圆片升起而影子留底，正确配对后两层合拢。",
    acceptance: ["按物体大小不能过", "错误反馈 150ms 内出现", "不画答案虚线框"],
  }),
  defineLevel({
    traceId: "TH-DC-005",
    number: 5,
    chapter: 1,
    role: "compose",
    legacyId: 5,
    legacySlug: "amber-triangle",
    controller: "light-drag",
    evidence: ["纸架真实中心线始终水平", "移动灯会同步改变三道影长"],
    hypotheses: ["重排砝码", "移动支点", "调整光源消除投影假象"],
    reasoningSteps: ["排除物体和支点失衡", "移动光源使三道影子等长"],
    negativeFeedback: ["重排只交换影形", "错误方向让影长差连续扩大"],
    hints: {
      h0: { content: "灯与影长持续共变", revealsAction: false },
      h1: { content: "水平基线短暂显现", revealsAction: false },
      h2: { content: "歪斜来自你看到的投影", revealsAction: false },
      h3: { content: "移动琥珀灯，让三道影子等长", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C1,
    knownAnswerMaxSeconds: 12,
    spatialProof: "灯和影处在不同深度，三条光路在等长时锁成三棱场。",
    acceptance: ["砝码重排不能过", "不要求单像素灯位", "低性能模式因果等价"],
  }),
  defineLevel({
    traceId: "TH-DC-006",
    number: 6,
    chapter: 1,
    role: "master",
    legacyId: 8,
    legacySlug: "relay-sandwich",
    controller: "layer-stack",
    evidence: ["两壳直接靠近会排斥", "透明片靠近一侧时另一侧也回应"],
    hypotheses: ["直接拼两壳", "三件任意叠放", "透明片作为中间关系层"],
    reasoningSteps: ["用双壳排斥排除直接拼合", "置中透明片后从两侧合壳"],
    negativeFeedback: ["双壳重叠产生反向弹力", "透明片在顶层或底层只激活一侧"],
    hints: {
      h0: { content: "薄片触发双侧回声", revealsAction: false },
      h1: { content: "中央纸层显一次折射边", revealsAction: false },
      h2: { content: "有一件东西不是外壳，而是关系", revealsAction: false },
      h3: { content: "把透明片夹在中间，再合上两壳", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C1,
    knownAnswerMaxSeconds: 15,
    spatialProof: "三层在 Z 轴分离，正确层序合成有厚度的时间核心。",
    acceptance: ["任意叠放不能过", "透明片不被永久遮住", "层序对键盘可读"],
  }),
  defineLevel({
    traceId: "TH-DC-007",
    number: 7,
    chapter: 2,
    role: "teach",
    legacyId: 13,
    legacySlug: "signal-oscillation",
    controller: "wave-align",
    evidence: ["两波同频但错相", "只有过零切口能够互补"],
    hypotheses: ["对齐波峰", "对齐颜色节点", "对齐共同零点"],
    reasoningSteps: ["错误对齐仍保留漏光", "水平移动让零点切口重合"],
    negativeFeedback: ["波峰重合时切口仍漏光", "颜色节点重合时刻线仍错位"],
    hints: {
      h0: { content: "错误对齐保留漏光", revealsAction: false },
      h1: { content: "两个零点切口各压一次", revealsAction: false },
      h2: { content: "共同点不一定在最高处", revealsAction: false },
      h3: { content: "让两个过零切口重合", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C2,
    knownAnswerMaxSeconds: 8,
    spatialProof: "相位差表现为层间剪切，正确零点形成贯穿针孔。",
    acceptance: ["波峰对齐不能过", "只允许水平调相", "零点视觉可辨"],
  }),
  defineLevel({
    traceId: "TH-DC-008",
    number: 8,
    chapter: 2,
    role: "twist",
    legacyId: 14,
    legacySlug: "corner-cross",
    controller: "coupled-drag",
    evidence: ["一条带移动会让另一条镜像响应", "两条切口轨迹指向同一中心"],
    hypotheses: ["分别拖到终点", "让两端彼此相接", "利用耦合共享一个中心"],
    reasoningSteps: ["试探确认镜像比例稳定", "一次耦合拖动同时对准双轴"],
    negativeFeedback: ["单轴只锁住一条压痕", "离开磁吸区立即释放重试"],
    hints: {
      h0: { content: "拖动时联动清晰可见", revealsAction: false },
      h1: { content: "中心横纵压痕先后变深", revealsAction: false },
      h2: { content: "移动的是一条，改变的是一个系统", revealsAction: false },
      h3: { content: "利用镜像联动，让两切口同时到中央", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C2,
    knownAnswerMaxSeconds: 8,
    spatialProof: "双带在不同深度交叉，锁成空间铰链。",
    acceptance: ["单轴不能过", "不要求两指精调", "磁吸区至少 36px"],
  }),
  defineLevel({
    traceId: "TH-DC-009",
    number: 9,
    chapter: 2,
    role: "twist",
    legacyId: 18,
    legacySlug: "outer-ones",
    controller: "resize",
    evidence: ["刻痕只能沿圆环外缘滑动", "圆环边缘拥有独立缩放抓手"],
    hypotheses: ["拖刻痕入环", "合并刻痕", "改变边界让外侧成为内侧"],
    reasoningSteps: ["确认对象跨不过边界", "放大环把两枚刻痕包入内域"],
    negativeFeedback: ["刻痕碰边界只沿切线滑动", "缩小环强化外侧关系"],
    hints: {
      h0: { content: "刻痕始终沿外缘滑动", revealsAction: false },
      h1: { content: "双层环边做一次内外呼吸", revealsAction: false },
      h2: { content: "也许该改变里面的范围", revealsAction: false },
      h3: { content: "放大圆环，把刻痕包进去", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C2,
    knownAnswerMaxSeconds: 8,
    spatialProof: "纸筒沿深度展开而刻痕保持世界坐标。",
    acceptance: ["刻痕合并不能过", "浏览器缩放不参与", "单指抓手可用"],
  }),
  defineLevel({
    traceId: "TH-DC-010",
    number: 10,
    chapter: 2,
    role: "compose",
    legacyId: 19,
    legacySlug: "double-housing-loop",
    controller: "rotate",
    evidence: ["同向缺口让夹层持续漏光", "旋外壳时内壳反向旋转"],
    hypotheses: ["把缺口重合", "分别补壳", "让相对缺口使夹层闭环"],
    reasoningSteps: ["重合缺口仍断排除直觉", "观察夹层并把缺口转到相对两侧"],
    negativeFeedback: ["同向重合只增强中心亮度", "接近正确关系时漏光连续缩短"],
    hints: {
      h0: { content: "泄光来自两壳之间", revealsAction: false },
      h1: { content: "夹层弧线显现一次", revealsAction: false },
      h2: { content: "需要完整的不是任何一个壳", revealsAction: false },
      h3: { content: "把两个缺口转到相对两侧", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C2,
    knownAnswerMaxSeconds: 12,
    spatialProof: "内外壳反向旋转，夹层亮成有厚度的闭环。",
    acceptance: ["缺口重叠不能过", "角度容差宽松", "数字在闭环前层"],
  }),
  defineLevel({
    traceId: "TH-DC-011",
    number: 11,
    chapter: 2,
    role: "teach",
    legacyId: 20,
    legacySlug: "quiet-circuit",
    controller: "focus-route",
    evidence: ["点击节点会断路", "经过外围光晕会让线路生长"],
    hypotheses: ["依次点击节点", "长按中心", "只让注意力沿外围经过"],
    reasoningSteps: ["用点击获得短路反证", "沿外围连续经过三节点"],
    negativeFeedback: ["激活中心产生短路纹", "偏离通道只回退当前段"],
    hints: {
      h0: { content: "点击断路、经过生长", revealsAction: false },
      h1: { content: "外围光晕依次扩一次", revealsAction: false },
      h2: { content: "它需要注意力，不需要按下", revealsAction: false },
      h3: { content: "沿外围经过三个节点，不点中心", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C2,
    knownAnswerMaxSeconds: 15,
    spatialProof: "中心与可走光晕分层，纸下电路逐段升起。",
    acceptance: ["点击三点不能过", "路径通道至少 44px", "手机无 hover 也可完成"],
  }),
  defineLevel({
    traceId: "TH-DC-012",
    number: 12,
    chapter: 2,
    role: "master",
    legacyId: 34,
    legacySlug: "double-horizon",
    controller: "layer-stack",
    evidence: ["天空和倒影都缺一条边", "两张纸的撕口互补且方向相反"],
    hypotheses: ["寻找第三张纸", "直接重叠两景", "旋叠两景共享一条边"],
    reasoningSteps: ["直接重叠得到双地平线反证", "旋转并调整层序共享地平线"],
    negativeFeedback: ["随意重叠产生双线重影", "错误层序使倒影浮在天空上"],
    hints: {
      h0: { content: "两张纸的撕口共变", revealsAction: false },
      h1: { content: "两条缺失边缘各显一次", revealsAction: false },
      h2: { content: "它们缺少的也许是同一条边", revealsAction: false },
      h3: { content: "旋转叠放，让天空和倒影共享地平线", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C2,
    knownAnswerMaxSeconds: 15,
    spatialProof: "两张景纸从不同深度收束为一条真实地平线。",
    acceptance: ["随意重叠不能过", "不使用答案虚线框", "移动端对象可滚动到达"],
  }),
  defineLevel({
    traceId: "TH-DC-013",
    number: 13,
    chapter: 3,
    role: "teach",
    legacyId: 23,
    legacySlug: "slow-clap",
    controller: "shadow-sort",
    evidence: ["花瓣拥有不同持续衰减", "沉默空隙也有不同长度"],
    hypotheses: ["按物体大小排序", "按颜色配对", "按持续时间匹配空间长度"],
    reasoningSteps: ["拖动花瓣观察空隙同长呼吸", "排除颜色和外形", "按时长完成三组配对"],
    negativeFeedback: ["外形入窝但尾音越界", "颜色匹配只改变色相"],
    hints: {
      h0: { content: "花瓣与空隙按同一时长呼吸", revealsAction: false },
      h1: { content: "三段空隙按长短显一次", revealsAction: false },
      h2: { content: "这里比较的是持续多久", revealsAction: false },
      h3: { content: "让声纹匹配相同时长的沉默", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C3,
    knownAnswerMaxSeconds: 15,
    spatialProof: "花瓣沉入时间槽，三段深度合成节奏花冠。",
    acceptance: ["大小和颜色不能误过", "静音可完成", "不要求现场打拍"],
  }),
  defineLevel({
    traceId: "TH-DC-014",
    number: 14,
    chapter: 3,
    role: "compose",
    legacyId: 24,
    legacySlug: "precision-five",
    controller: "rhythm",
    evidence: ["墨珠沿曲线恒速运动", "四段路程为短长短长"],
    hypotheses: ["快速点击五次", "按颜色决定节奏", "把恒速路径长度读成时间间隔"],
    reasoningSteps: ["描线确认速度不变", "把距离转成短长间隔", "复现五拍"],
    negativeFeedback: ["等间隔会产生错误等长影", "每段独立显示关系错误"],
    hints: {
      h0: { content: "恒速墨珠展示距离与时间", revealsAction: false },
      h1: { content: "四段路程交替加深", revealsAction: false },
      h2: { content: "相同速度下，距离就是等待", revealsAction: false },
      h3: { content: "按短、长、短、长间隔敲五拍", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C3,
    knownAnswerMaxSeconds: 20,
    spatialProof: "节点按时间远近形成阶梯，节拍脉冲沿路程传播。",
    acceptance: ["等间隔不能过", "逐间隔容差至少 ±35%", "失败不重描路径"],
  }),
  defineLevel({
    traceId: "TH-DC-015",
    number: 15,
    chapter: 3,
    role: "twist",
    legacyId: 27,
    legacySlug: "beacon-metronome",
    controller: "orbit",
    evidence: ["光束速度恒定", "迟到点与前一点角距离更大"],
    hypotheses: ["改变光束速度", "点击校准迟到点", "改变距离来改变时间间隔"],
    reasoningSteps: ["确认光束速度锁定", "移动点观察时刻同步变化", "让四段角距均匀"],
    negativeFeedback: ["点击光束只显示锁定刻线", "错误移动使间隔连续变差"],
    hints: {
      h0: { content: "点位与亮起时刻共变", revealsAction: false },
      h1: { content: "环上距离刻纹显一次", revealsAction: false },
      h2: { content: "光没有变慢，路变长了", revealsAction: false },
      h3: { content: "把迟到点移到与其他点等距", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C3,
    knownAnswerMaxSeconds: 12,
    spatialProof: "浅 3D 轨道把角距离和时间尾迹直接关联。",
    acceptance: ["不允许改光速", "角距误差容许 12%", "不要求毫秒调节"],
  }),
  defineLevel({
    traceId: "TH-DC-016",
    number: 16,
    chapter: 3,
    role: "compose",
    legacyId: 29,
    legacySlug: "pulse-checker",
    controller: "shared-control",
    evidence: ["刻带近似等距但缺一点", "检查尺能消隐与自身重合的刻线"],
    hypotheses: ["逐个间隙试墨点", "计算平均间距", "用比较工具消去相同信息"],
    reasoningSteps: ["对齐检查尺建立基准", "识别唯一亮槽", "用备用墨点补齐"],
    negativeFeedback: ["错槽显示相邻间距矛盾", "尺错相时多个槽同时亮"],
    hints: {
      h0: { content: "覆盖后相同刻线消失", revealsAction: false },
      h1: { content: "检查尺边缘压印一次", revealsAction: false },
      h2: { content: "先让相同的消失，差异才会出现", revealsAction: false },
      h3: { content: "对齐检查尺，再补唯一亮槽", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C3,
    knownAnswerMaxSeconds: 15,
    spatialProof: "刻带、折射尺和墨点三层合成完整脉冲尺。",
    acceptance: ["逐槽穷举受反证约束", "检查尺必须改变信息", "尺位置宽松吸附"],
  }),
  defineLevel({
    traceId: "TH-DC-017",
    number: 17,
    chapter: 3,
    role: "twist",
    legacyId: 30,
    legacySlug: "broken-measure",
    controller: "fold",
    evidence: ["四拍标记只对应三条正面线", "厚折角边缘透出背面墨"],
    hypotheses: ["点击四个节点", "手动画第四线", "翻纸找到背面缺拍"],
    reasoningSteps: ["用无反馈点击排除演奏", "观察背墨和折角", "翻平背线接入谱面"],
    negativeFeedback: ["节点只留下普通压痕", "错误折向让背线远离缺口"],
    hints: {
      h0: { content: "纸边透墨且厚度异常", revealsAction: false },
      h1: { content: "折角阴影短促加深", revealsAction: false },
      h2: { content: "缺少的拍不一定在正面", revealsAction: false },
      h3: { content: "翻开折角，把背面第四线接回来", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C3,
    knownAnswerMaxSeconds: 8,
    spatialProof: "纸页沿铰链翻转，背线从另一 Z 面接入。",
    acceptance: ["四次点击不能过", "标题不直接提示折角", "WebKit 背面不镜像"],
  }),
  defineLevel({
    traceId: "TH-DC-018",
    number: 18,
    chapter: 3,
    role: "master",
    legacyId: 39,
    legacySlug: "tab-doubleback",
    controller: "layer-stack",
    evidence: ["丝带断端纹理相同但翻面", "两个页签留下相反上下压痕"],
    hypotheses: ["直接接断端", "移开页签", "按前后层级穿过两页签"],
    reasoningSteps: ["直连获得穿模反证", "读取上下压痕", "按后穿再前穿接回自身"],
    negativeFeedback: ["位置对齐但纹理翻面", "正确单段层级会保留"],
    hints: {
      h0: { content: "断端匹配但层级不匹配", revealsAction: false },
      h1: { content: "两处上下压痕依次加深", revealsAction: false },
      h2: { content: "路线还包含靠前和靠后", revealsAction: false },
      h3: { content: "先从第一页签后穿，再从第二页签前穿", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C3,
    knownAnswerMaxSeconds: 20,
    spatialProof: "丝带在有厚度页签之间连续前后穿层。",
    acceptance: ["固定滑序不能绕过层级", "通道至少 44px", "当前前后层可访问"],
  }),
  defineLevel({
    traceId: "TH-DC-019",
    number: 19,
    chapter: 4,
    role: "teach",
    legacyId: 43,
    legacySlug: "archive-route",
    controller: "focus-route",
    evidence: ["点击页签会中断路线", "当前注意力投出下一段光带"],
    hypotheses: ["依次打开页签", "按编号点击", "沿光带移动焦点而不激活"],
    reasoningSteps: ["点击获取断路反证", "沿当前光带找下一段", "不激活内容到达终点"],
    negativeFeedback: ["打开内容使路线断开", "偏离只回退当前段"],
    hints: {
      h0: { content: "当前焦点投出下一段", revealsAction: false },
      h1: { content: "起点页签边缘轻压一次", revealsAction: false },
      h2: { content: "路线只对注意力显形", revealsAction: false },
      h3: { content: "沿光带移动焦点，不打开页签", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C4,
    knownAnswerMaxSeconds: 20,
    spatialProof: "焦点光在不同纸层间接力，收束为纵深曲线。",
    acceptance: ["打开页签不能过", "无 hover 设备可发现", "H1 不画完整路线"],
  }),
  defineLevel({
    traceId: "TH-DC-020",
    number: 20,
    chapter: 4,
    role: "compose",
    legacyId: 45,
    legacySlug: "focus-cascade",
    controller: "focus-route",
    evidence: ["聚焦一层会改变相邻层清晰度", "纸边箭头指示深到浅的传递"],
    hypotheses: ["从左到右聚焦", "同时点亮四层", "从最深层传递清晰度"],
    reasoningSteps: ["错误顺序显示清晰度被吞回", "找唯一深层起点", "逐层送到前景"],
    negativeFeedback: ["错误层只影响相邻两层", "重复聚焦形成闭环压痕"],
    hints: {
      h0: { content: "焦点影响邻层", revealsAction: false },
      h1: { content: "最深纸层边缘显色", revealsAction: false },
      h2: { content: "清晰度也有流向", revealsAction: false },
      h3: { content: "从最深层顺箭头送到前面", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C4,
    knownAnswerMaxSeconds: 20,
    spatialProof: "折射焦平面沿四层逐层前移并合焦。",
    acceptance: ["左到右穷举不能误过", "必要文字不依赖模糊阅读", "布局变化仍可推理"],
  }),
  defineLevel({
    traceId: "TH-DC-021",
    number: 21,
    chapter: 4,
    role: "twist",
    legacyId: 48,
    legacySlug: "pause-word",
    controller: "patient-hold",
    evidence: ["文字持续移动且被按会加速", "文字间一块空白始终固定"],
    hypotheses: ["点击正确字母", "追帧停住 PAUSE", "把固定空白当控制面"],
    reasoningSteps: ["排除追逐移动文字", "确认空白是稳定参照", "按住空白等待交会"],
    negativeFeedback: ["点击文字只让它加速", "按错空白只局部减速"],
    hints: {
      h0: { content: "文字移动而空白固定", revealsAction: false },
      h1: { content: "固定空白两边缘同时压一次", revealsAction: false },
      h2: { content: "不要追正在移动的东西", revealsAction: false },
      h3: { content: "按住不动的空白", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C4,
    knownAnswerMaxSeconds: 8,
    spatialProof: "固定空白成为贯穿多层文字带的透明孔。",
    acceptance: ["不要求精确一帧", "reduced-motion 保留固定参照", "文字不遮数字"],
  }),
  defineLevel({
    traceId: "TH-DC-022",
    number: 22,
    chapter: 4,
    role: "compose",
    legacyId: 50,
    legacySlug: "mirrored-input",
    controller: "layer-stack",
    evidence: ["拖一枚标点会让另一带镜像", "中央槽同时匹配两种句末"],
    hypotheses: ["切语言分别解答", "各放一枚标点", "叠句带共享一个位置"],
    reasoningSteps: ["单独满足一种语言获得矛盾", "识别镜像联动", "同时满足两个句末"],
    negativeFeedback: ["一条正确时另一条倒影断裂", "层序错误时句带遮挡不成立"],
    hints: {
      h0: { content: "拖一枚、另一枚镜像", revealsAction: false },
      h1: { content: "共享空槽显一次双面纤维", revealsAction: false },
      h2: { content: "两个句末不能分开解决", revealsAction: false },
      h3: { content: "叠句带让共享槽同时成为句末", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C4,
    knownAnswerMaxSeconds: 15,
    spatialProof: "双语透明层以共享轴心收束为数字小数点。",
    acceptance: ["切语言不能过", "必须同时满足两规则", "字体度量不破坏几何"],
  }),
  defineLevel({
    traceId: "TH-DC-023",
    number: 23,
    chapter: 4,
    role: "compose",
    legacyId: 54,
    legacySlug: "hybrid-console",
    controller: "coupled-drag",
    evidence: ["单独绕带会被纸轴反弹", "持续按轴会消除反弹但不绕行"],
    hypotheses: ["更快绕圈", "先固定再松手绕", "固定与绕行必须重叠"],
    reasoningSteps: ["分别尝试两个输入角色", "识别时间重叠条件", "固定轴同时绕完一圈"],
    negativeFeedback: ["单输入按比例退回", "依次动作显示未重叠时间条"],
    hints: {
      h0: { content: "绕行反弹、固定消除反弹", revealsAction: false },
      h1: { content: "轴压纹和环行箭头各回应", revealsAction: false },
      h2: { content: "两个动作不是先后关系", revealsAction: false },
      h3: { content: "按住纸轴，同时让丝带绕一圈", revealsAction: true },
    },
    solveShape: "concurrent",
    firstSolveTargetSeconds: C4,
    knownAnswerMaxSeconds: 15,
    spatialProof: "固定轴与立体螺旋形成可见发条因果。",
    acceptance: ["依次动作不能过", "纯键盘路径等价", "不保存轨迹"],
  }),
  defineLevel({
    traceId: "TH-DC-024",
    number: 24,
    chapter: 4,
    role: "master",
    legacyId: 74,
    legacySlug: "clue-relay-braid",
    controller: "layer-stack",
    evidence: ["遮挡顺序会改变句义", "三条纸边纹理给出上下关系"],
    hypotheses: ["按语义排序", "完全不遮挡", "按织纹建立两次交叉层级"],
    reasoningSteps: ["尝试叠放观察句义变化", "排除全局 z-index 穷举", "按上下载纹完成编织"],
    negativeFeedback: ["错误层序生成自相矛盾短句", "边缘指出违反的上下关系"],
    hints: {
      h0: { content: "遮挡改变词义", revealsAction: false },
      h1: { content: "三条纸边纹理依次显色", revealsAction: false },
      h2: { content: "句子缺少的是谁从谁上面经过", revealsAction: false },
      h3: { content: "按纹理编成上、下、上的交叉层级", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C4,
    knownAnswerMaxSeconds: 20,
    spatialProof: "三条句带在 Z 轴交替穿行，负空间显出隐藏词。",
    acceptance: ["全局层序穷举不能秒过", "纹理提供公平依据", "双语不泄题"],
  }),
  defineLevel({
    traceId: "TH-DC-025",
    number: 25,
    chapter: 5,
    role: "teach",
    legacyId: 40,
    legacySlug: "tab-return",
    controller: "cover-return",
    evidence: ["半张纸票被抓会向外躲", "停止追逐或遮住页面会让它返回"],
    hypotheses: ["更快抓取", "从另一侧拖入", "让页面经历不可见再可见"],
    reasoningSteps: ["抓取获得逃离反证", "停手观察返回趋势", "用真实可见性或盖页完成状态循环"],
    negativeFeedback: ["连续抓取只让纸票更远", "盖页未完全覆盖只返回半张"],
    hints: {
      h0: { content: "停手后纸票回弹", revealsAction: false },
      h1: { content: "盖页把手边缘显一次", revealsAction: false },
      h2: { content: "它需要被重新看见", revealsAction: false },
      h3: { content: "离开再回来，或完全盖住后揭开", revealsAction: true },
    },
    solveShape: "stateful",
    firstSolveTargetSeconds: C5,
    knownAnswerMaxSeconds: 12,
    spatialProof: "返回首帧纸票从页面后层完整归位。",
    acceptance: ["首次 visibility 不误过", "关内盖页为后备", "不采集标签信息"],
  }),
  defineLevel({
    traceId: "TH-DC-026",
    number: 26,
    chapter: 5,
    role: "twist",
    legacyId: 61,
    legacySlug: "reverse-sweep",
    controller: "shared-control",
    evidence: ["把手和云影移动方向相反", "尺上有唯一无刻度位"],
    hypotheses: ["顺目标方向拖", "翻正纸尺", "利用反向映射送缺口"],
    reasoningSteps: ["小幅试探确认反向", "排除翻尺", "用世界坐标反向控制对齐"],
    negativeFeedback: ["直觉方向让误差扩大", "纸尺背面仍然反写"],
    hints: {
      h0: { content: "首次小拖显示反向关系", revealsAction: false },
      h1: { content: "无刻度位压一次", revealsAction: false },
      h2: { content: "控制方向变了，目标没有", revealsAction: false },
      h3: { content: "反向拖把手，让云缺口到无刻度处", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C5,
    knownAnswerMaxSeconds: 8,
    spatialProof: "前层把手和后层云影由反向力杆连接。",
    acceptance: ["累计距离不能过", "目标区至少 44px", "不做方向密码"],
  }),
  defineLevel({
    traceId: "TH-DC-027",
    number: 27,
    chapter: 5,
    role: "compose",
    legacyId: 65,
    legacySlug: "long-archive-route",
    controller: "focus-route",
    evidence: ["标签文字每局变化", "三角影方向保持稳定"],
    hypotheses: ["记文字顺序", "按位置颜色走", "把影子读成有向边"],
    reasoningSteps: ["确认文字不可靠", "找唯一无入边起点", "沿影向走到无出边终点"],
    negativeFeedback: ["固定记忆在新布局首步矛盾", "错误节点形成回环压痕"],
    hints: {
      h0: { content: "焦点只强化当前影向", revealsAction: false },
      h1: { content: "无入边节点的纸面轻抬", revealsAction: false },
      h2: { content: "会变的是名字，不变的是方向", revealsAction: false },
      h3: { content: "从无入边处沿影走到无出边处", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C5,
    knownAnswerMaxSeconds: 25,
    spatialProof: "影子跨档案塔层投射，正确路线逐层对齐。",
    acceptance: ["固定序列不能过", "只用可验证唯一解模板", "错误只回最近分叉"],
  }),
  defineLevel({
    traceId: "TH-DC-028",
    number: 28,
    chapter: 5,
    role: "twist",
    legacyId: 67,
    legacySlug: "wheel-echo",
    controller: "wheel-echo",
    evidence: ["实体滚动波纹与缺口材质不同", "半透明回声延迟反向返回"],
    hypotheses: ["实体波纹填缺口", "反向滚动直达", "控制延迟回声落位"],
    reasoningSteps: ["观察实体被排斥", "等待并识别回声", "利用反向关系让回声入槽"],
    negativeFeedback: ["实体波纹材质相斥", "高速多回声互相抵消"],
    hints: {
      h0: { content: "延迟回声清楚可见", revealsAction: false },
      h1: { content: "半透明缺弧回应一次", revealsAction: false },
      h2: { content: "最先出现的不是要留下的", revealsAction: false },
      h3: { content: "让滚动后的反向回声填缺弧", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C5,
    knownAnswerMaxSeconds: 8,
    spatialProof: "实体在前层离开，回声从后层返回锁入纸轮。",
    acceptance: ["不全局禁滚", "实体不能过", "高速累计不能过"],
  }),
  defineLevel({
    traceId: "TH-DC-029",
    number: 29,
    chapter: 5,
    role: "master",
    legacyId: 69,
    legacySlug: "archive-figure-eight",
    controller: "trace",
    evidence: ["左右章瓣共享中央交叉压痕", "两个分开圆无法留下共享墨"],
    hypotheses: ["画两个圆", "画外轮廓", "一笔双瓣并两次穿中心"],
    reasoningSteps: ["用分开圆排除外形近似", "识别中心的拓扑要求", "连续完成双瓣自交闭合"],
    negativeFeedback: ["分开圆中心断墨", "中心摩擦不累计成穿越"],
    hints: {
      h0: { content: "中央压痕对两侧同时回应", revealsAction: false },
      h1: { content: "中心交叉只压一次", revealsAction: false },
      h2: { content: "重要的是一笔怎样穿过中心", revealsAction: false },
      h3: { content: "连续画八字，左右闭合并两穿中央", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C5,
    knownAnswerMaxSeconds: 20,
    spatialProof: "两次中心穿越交替上下层，形成空间双环。",
    acceptance: ["两个圆不能过", "判拓扑不判像素模板", "不保存轨迹"],
  }),
  defineLevel({
    traceId: "TH-DC-030",
    number: 30,
    chapter: 5,
    role: "master",
    legacyId: 84,
    legacySlug: "ghost-session",
    controller: "cover-return",
    evidence: ["纸点移动后留下浅影", "本关重置复位纸点但保留有依据的影"],
    hypotheses: ["寻找完整圆槽", "快速在两处移动", "用重置跨状态合成一圆"],
    reasoningSteps: ["在半圆压痕留下影", "重置确认历史层保留", "把当前点放到互补半圆"],
    negativeFeedback: ["无依据影在重置后淡出", "错误第二位置显示无法闭圆"],
    hints: {
      h0: { content: "移动后浅影可见", revealsAction: false },
      h1: { content: "重来后旧影保持一次", revealsAction: false },
      h2: { content: "这次重来没有清除所有东西", revealsAction: false },
      h3: { content: "半圆留影、重来、再放互补半圆", revealsAction: true },
    },
    solveShape: "stateful",
    firstSolveTargetSeconds: C5,
    knownAnswerMaxSeconds: 15,
    spatialProof: "历史层与现在层在重置后合为完整时间圆。",
    acceptance: ["不改全局重试语义", "只需一次重置", "离关清理临时影"],
  }),
  defineLevel({
    traceId: "TH-DC-031",
    number: 31,
    chapter: 6,
    role: "compose",
    legacyId: 86,
    legacySlug: "eclipse-session",
    controller: "shared-control",
    evidence: ["真实菜单纸有圆形缺口", "缺口与太阳边缘折射相同"],
    hypotheses: ["菜单有隐藏开关", "点击太阳", "用功能纸层制造日食并转移圆影"],
    reasoningSteps: ["确认菜单项只是正常设置", "拖纸层套住太阳", "关闭菜单让圆影落到小数点"],
    negativeFeedback: ["仅开关菜单没有进展", "套其他圆饰只产生普通遮挡"],
    hints: {
      h0: { content: "菜单缺口与太阳边缘共振", revealsAction: false },
      h1: { content: "菜单可拖纸边轻压一次", revealsAction: false },
      h2: { content: "菜单本身也是一张纸", revealsAction: false },
      h3: { content: "缺口套太阳，再关闭留下圆影", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C6,
    knownAnswerMaxSeconds: 15,
    spatialProof: "前景菜单孔贯穿背景太阳，圆影落到数字轴心。",
    acceptance: ["菜单项保持真实可用", "开关本身不能过", "焦点管理完整"],
  }),
  defineLevel({
    traceId: "TH-DC-032",
    number: 32,
    chapter: 6,
    role: "compose",
    legacyId: 89,
    legacySlug: "device-braid",
    controller: "resize",
    evidence: ["关内视口宽度会真正重排内容", "中央纸夹可保留窄版痕迹"],
    hypotheses: ["改真实浏览器宽度", "单宽度直接接线", "保存窄版关系再展开宽版"],
    reasoningSteps: ["确认关内是重排而非缩放", "窄版夹住点带", "展开后让宽带从历史痕迹下穿"],
    negativeFeedback: ["真实窗口变化不计判定", "未夹住就展开会丢失窄版痕迹"],
    hints: {
      h0: { content: "小视口宽度改写布局", revealsAction: false },
      h1: { content: "窄版中央纸夹压一次", revealsAction: false },
      h2: { content: "先保留一个宽度里的关系", revealsAction: false },
      h3: { content: "窄版夹点带，再展开让宽带下穿", revealsAction: true },
    },
    solveShape: "stateful",
    firstSolveTargetSeconds: C6,
    knownAnswerMaxSeconds: 25,
    spatialProof: "历史窄版层与当前宽版层编成响应式织带。",
    acceptance: ["真实 resize 不能过", "360/390/平板均可达阈值", "页面可正常滚动"],
  }),
  defineLevel({
    traceId: "TH-DC-033",
    number: 33,
    chapter: 6,
    role: "master",
    legacyId: 93,
    legacySlug: "six-beat-lock",
    controller: "fold",
    evidence: ["六段长短关系与折线位置吻合", "直接演奏不改变世界"],
    hypotheses: ["敲六拍", "连接六端", "折叠压缩时间距离"],
    reasoningSteps: ["用演奏无反馈排除节拍输入", "识别长包短关系", "沿折线让六端重合"],
    negativeFeedback: ["错误折向只形成部分端点组", "正确部分折叠会保留"],
    hints: {
      h0: { content: "折线与长包短关系可见", revealsAction: false },
      h1: { content: "六端依次压出同心影", revealsAction: false },
      h2: { content: "不是演奏，而是缩短拍间距离", revealsAction: false },
      h3: { content: "沿折线折纸，让六端压到一起", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C6,
    knownAnswerMaxSeconds: 25,
    spatialProof: "每次折叠增加纸层厚度，六段压成单拍印章。",
    acceptance: ["六次点击不能过", "折序可交换", "最终关系而非动作脚本判定"],
  }),
  defineLevel({
    traceId: "TH-DC-034",
    number: 34,
    chapter: 6,
    role: "master",
    legacyId: 95,
    legacySlug: "triple-phase",
    controller: "layer-stack",
    evidence: ["三片缺口互补可成圆", "错误时间层序产生方向重影"],
    hypotheses: ["只需重叠", "按颜色排序", "同时满足位置和时间先后"],
    reasoningSteps: ["先叠形状发现仍有重影", "读取纸边因果压痕", "按过去现在未来重排并对齐"],
    negativeFeedback: ["完整圆但错序保留重影", "颜色序使因果箭头断裂"],
    hints: {
      h0: { content: "错层序产生方向性重影", revealsAction: false },
      h1: { content: "纸边先后压痕依序显色", revealsAction: false },
      h2: { content: "完整形状还不够，时间也有前后", revealsAction: false },
      h3: { content: "过去下、现在中、未来上并对齐", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C6,
    knownAnswerMaxSeconds: 15,
    spatialProof: "三张时间片沿 Z 轴收束到同一现在焦平面。",
    acceptance: ["仅重叠或仅排序不能过", "层序与位置分开操控", "重影不影响文字"],
  }),
  defineLevel({
    traceId: "TH-DC-035",
    number: 35,
    chapter: 6,
    role: "master",
    legacyId: 99,
    legacySlug: "relay-polyrhythm",
    controller: "wave-align",
    evidence: ["二分波与三分波存在共同交点", "六孔检查带会消隐非共同点"],
    hypotheses: ["点击 2/3/6 次", "对齐波峰", "把复节奏转成空间交集"],
    reasoningSteps: ["用点击排除演奏", "移动检查带识别共同点", "整体对齐六孔周期"],
    negativeFeedback: ["次数点击只强化单波", "错相时部分孔为空"],
    hints: {
      h0: { content: "检查带消隐非共同点", revealsAction: false },
      h1: { content: "六孔按共同周期显一次", revealsAction: false },
      h2: { content: "找两种节奏同时成立的位置", revealsAction: false },
      h3: { content: "整体移动六孔带对准共同交点", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C6,
    knownAnswerMaxSeconds: 15,
    spatialProof: "六个共同交点形成贯穿两波与检查带的短柱。",
    acceptance: ["按次数不能过", "只判整体相位", "空间柱不遮数字"],
  }),
  defineLevel({
    traceId: "TH-DC-036",
    number: 36,
    chapter: 6,
    role: "master",
    legacyId: 100,
    legacySlug: "silent-constellation",
    controller: "constellation",
    evidence: ["两组星群靠近会改变中央负空间", "负空间显出 V 和三个语义交点"],
    hypotheses: ["连接所有亮星", "直接画任意 V", "先显出负空间规则再利用"],
    reasoningSteps: ["用无依据连线排除表面星座", "收拢两组星显出 V", "沿负空间三个交点完成 V"],
    negativeFeedback: ["随意点星只留不闭合短线", "未显出负空间前画 V 不计解答"],
    hints: {
      h0: { content: "星群靠近时中央空白变化", revealsAction: false },
      h1: { content: "只让负空间边缘显一次", revealsAction: false },
      h2: { content: "最后的形状在两边之间", revealsAction: false },
      h3: { content: "收拢星群显 V，再沿三交点画 V", revealsAction: true },
    },
    solveShape: "sequence",
    firstSolveTargetSeconds: C6,
    knownAnswerMaxSeconds: 20,
    spatialProof: "两层星群之间形成真实空洞，V 贯穿到时间核心。",
    acceptance: ["resize 和缩放不能过", "不启用摄像头", "轨迹不做像素模板"],
  }),
]);

export const DIRECTOR_CAMPAIGN_BY_LEGACY_SLUG: ReadonlyMap<
  string,
  DirectorLevelDefinition
> = new Map(DIRECTOR_CAMPAIGN.map((level) => [level.legacySlug, level]));

export function directorLevelByNumber(number: number): DirectorLevelDefinition | null {
  if (!Number.isInteger(number) || number < 1 || number > DIRECTOR_CAMPAIGN.length) {
    return null;
  }
  return DIRECTOR_CAMPAIGN[number - 1] ?? null;
}
