import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const bible = readFileSync(resolve(root, "docs/plans/2026-08-08-time-hacker-v2-100-level-design-bible.md"), "utf8");
const matrix = readFileSync(resolve(root, "docs/plans/2026-08-08-time-hacker-v2-100-level-diversity-matrix.md"), "utf8");

type Controller =
  | "corner-repair"
  | "patient-hold"
  | "word-shift"
  | "shadow-sort"
  | "light-drag"
  | "trace"
  | "frame-drag"
  | "layer-stack"
  | "fold"
  | "coupled-drag"
  | "wave-align"
  | "flip"
  | "orbit"
  | "resize"
  | "focus-route"
  | "rhythm"
  | "wheel-echo"
  | "cover-return"
  | "rotate"
  | "edge-route"
  | "shared-control"
  | "constellation";

function controllerFor(id: number, input: string): Controller {
  const special: Record<number, Controller> = {
    1: "corner-repair", 2: "patient-hold", 3: "word-shift", 40: "cover-return",
    4: "shadow-sort", 6: "trace", 9: "shadow-sort", 10: "fold", 11: "patient-hold", 12: "patient-hold",
    22: "rhythm", 25: "rhythm", 34: "layer-stack", 38: "edge-route", 47: "patient-hold", 51: "fold",
    54: "coupled-drag", 62: "shared-control", 72: "layer-stack", 73: "shadow-sort",
    67: "wheel-echo", 69: "trace", 85: "cover-return", 92: "shared-control", 100: "constellation",
  };
  if (special[id]) return special[id];
  if (/光源|拖光|遮光/.test(input)) return "light-drag";
  if (/影子|排序|配对|归位|移除/.test(input)) return "shadow-sort";
  if (/等待|长按|按住|时机|单次触碰|单触/.test(input)) return "patient-hold";
  if (/节拍|打拍|敲击|节奏/.test(input)) return "rhythm";
  if (/focus|hover|焦点|悬停|注意力/.test(input)) return "focus-route";
  if (/滚动|滚轮/.test(input)) return "wheel-echo";
  if (/visibility|盖页|重置/.test(input)) return "cover-return";
  if (/轨迹|描线|擦拭|擦出|穿越|边缘拖动|短段边缘/.test(input)) return "trace";
  if (/折|翻页|翻词带|合页/.test(input)) return "fold";
  if (/翻片|翻转|单片翻转/.test(input)) return "flip";
  if (/旋|档位/.test(input)) return "rotate";
  if (/缩放|视口|调视口|放大环/.test(input)) return "resize";
  if (/层|叠|编织|组装|三层|双带|双窗/.test(input)) return "layer-stack";
  if (/耦合|双输入|并发|共同|共享/.test(input)) return "coupled-drag";
  if (/波|水平拖带|对齐/.test(input)) return "wave-align";
  if (/框|窗/.test(input)) return "frame-drag";
  if (/边缘|穿层/.test(input)) return "edge-route";
  if (/环|轨道|径向/.test(input)) return "orbit";
  if (/拖|移动|搬|送/.test(input)) return "shared-control";
  return "shared-control";
}

function visualFor(id: number, controller: Controller) {
  const shapes = ["dot", "ring", "paper", "arc", "line"] as const;
  const count = 3 + id % 3;
  return {
    motif: controller,
    marks: Array.from({ length: count }, (_, index) => ({
      x: 6 + ((id * 17 + index * 29) % 88),
      y: 12 + ((id * 23 + index * 31) % 72),
      size: 18 + ((id * 11 + index * 13) % 54),
      rotation: (id * 19 + index * 47) % 180,
      shape: shapes[(id + index * 2) % shapes.length],
    })),
  };
}

const matrixRows = new Map<number, string[]>();
for (const line of matrix.split(/\r?\n/)) {
  const match = line.match(/^\|\s*(\d{3})\s*\|\s*`([^`]+)`\s*\|\s*([^|]+)\|\s*([^|]+)\|\s*([^|]+)\|\s*([^|]+)\|\s*([^|]+)\|\s*([^|]+)\|/);
  if (!match) continue;
  matrixRows.set(Number(match[1]), match.slice(2).map((value) => value.trim()));
}

const levelPattern = /^###\s+(\d{3})\s+(.+?)\s+\/\s+(.+?)\r?\n\r?\n- \*\*slug\*\*：`([^`]+)`\r?\n- \*\*场景与异常\*\*：(.+)\r?\n- \*\*发现 → 破解\*\*：(.+)\r?\n- \*\*反馈与提示\*\*：(.+)\r?\n- \*\*跨端与视觉\*\*：(.+)\r?\n- \*\*验收\*\*：(.+)$/gm;
const levels = [...bible.matchAll(levelPattern)].map((match) => {
  const id = Number(match[1]);
  const row = matrixRows.get(id);
  if (!row) throw new Error(`Missing diversity row ${match[1]}`);
  const [matrixSlug, discovery, solve, input, cognitiveShift, silhouette, risk] = row;
  if (matrixSlug !== match[4]) throw new Error(`Slug mismatch at ${match[1]}`);
  const controller = controllerFor(id, input);
  return {
    id,
    slug: match[4],
    title: { zh: match[2], en: match[3] },
    chapter: Math.ceil(id / 10),
    controller,
    visual: visualFor(id, controller),
    scene: match[5],
    walkthrough: match[6],
    feedback: match[7],
    crossPlatform: match[8],
    acceptance: match[9],
    discovery,
    solve,
    input,
    cognitiveShift,
    silhouette,
    risk,
  };
});

if (levels.length !== 100) throw new Error(`Expected 100 levels, found ${levels.length}`);
if (new Set(levels.map(({ slug }) => slug)).size !== 100) throw new Error("Level slugs are not unique");

const header = `/* This file is generated by scripts/generate-v2-level-registry.ts. */
export const V2_CONTROLLER_KINDS = [
  "corner-repair", "patient-hold", "word-shift", "shadow-sort", "light-drag", "trace",
  "frame-drag", "layer-stack", "fold", "coupled-drag", "wave-align", "flip", "orbit",
  "resize", "focus-route", "rhythm", "wheel-echo", "cover-return", "rotate", "edge-route",
  "shared-control", "constellation",
] as const;

export type V2ControllerKind = (typeof V2_CONTROLLER_KINDS)[number];

export interface V2LevelDefinition {
  id: number;
  slug: string;
  title: { zh: string; en: string };
  chapter: number;
  controller: V2ControllerKind;
  visual: {
    motif: V2ControllerKind;
    marks: ReadonlyArray<{ x: number; y: number; size: number; rotation: number; shape: "dot" | "ring" | "paper" | "arc" | "line" }>;
  };
  scene: string;
  walkthrough: string;
  feedback: string;
  crossPlatform: string;
  acceptance: string;
  discovery: string;
  solve: string;
  input: string;
  cognitiveShift: string;
  silhouette: string;
  risk: string;
}

export const V2_LEVELS = `;

writeFileSync(
  resolve(root, "src/game/v2-levels.generated.ts"),
  `${header}${JSON.stringify(levels, null, 2)} as const satisfies readonly V2LevelDefinition[];\n\nexport const V2_LEVEL_BY_SLUG: ReadonlyMap<string, V2LevelDefinition> = new Map(V2_LEVELS.map((level) => [level.slug, level]));\n`,
);

console.log(`Generated ${levels.length} V2 levels.`);
